module.exports = {
    'WASTE_EN_GB': {
        'paper': 'You should put paper into the blue box.',
        'card': 'You should put card into the blue box.',
        'newspaper': 'You should put newspaper into the blue box.',
        'newspapers': 'You should put newspapers into the blue box.',
        'magazine': 'You should put magazine into the blue box.',
        'magazines': 'You should put magazines into the blue box.',
        'shredded paper': 'You should put shredded paper into the blue box.',
        'envelope': 'You should put envelope into the blue box.',
        'envelopes': 'You should put envelopes into the blue box.',
        'cardboard': 'You should put cardboard into the blue box.',
        'cardboards': 'You should put cardboards into the blue box.',
        'junk mail': 'You should put junk mail into the blue box.',
        'cereal box': 'You should put cereal box into the blue box.',
        'toilet roll': 'You should put toilet roll into the blue box.',
        'toilet rolls': 'You should put toilet rolls into the blue box.',
        'corrugated cardboard': 'You should put corrugated cardboard into the blue box.',
        'corrugated cardboards': 'You should put corrugated cardboards into the blue box.',
        'tetrapack': 'You should put tetrapack into the blue box.',
        'carton': 'If it is food or juice cardboard (tetrapack), you should put it into the blue box.',
        'glass bottle': 'You should put glass bottle into the red box.',
        'glass bottles': 'You should put glass bottles into the red box.',
        'glass jar': 'You should put glass jar into the red box.',
        'glass jars': 'You should put glass jars into the red box.',
        'tin': 'You should put aluminium or steel tin into the black box.',
        'tins': 'You should put aluminium or steel tins into the black box.',
        'can': 'You should put aluminium or steel can into the black box.',
        'cans': 'You should put aluminium or steel cans into the black box.',
        'aluminium tin': 'You should put aluminium tin into the black box.',
        'aluminium tins': 'You should put aluminium tins into the black box.',
        'aluminium can': 'You should put aluminium can into the black box.',
        'aluminium cans': 'You should put aluminium cans into the black box.',
        'steel tin': 'You should put steel tin into the black box.',
        'steel tins': 'You should put steel tins into the black box.',
        'steel can': 'You should put steel can into the black box.',
        'steel cans': 'You should put steel cans into the black box.',
        'clean foil': 'You should put clean foil into the black box.',
        'foil': 'Only if it is clean you should put it into the black box, you cannot recycle dirty foil.',
        'aluminium tray': 'You should put aluminium tray into the black box.',
        'aluminium trays': 'You should put aluminium trays into the black box.',
        'plastic bottle': 'You should put plastic bottle into the black box.',
        'plastic bottles': 'You should put plastic bottles into the black box.',
        'plastic tube': 'You should put plastic tube into the black box.',
        'plastic tubes': 'You should put plastic tubes into the black box.',
        'plastic pot': 'You should put plastic pot into the black box.',
        'plastic pots': 'You should put plastic pots into the black box.',
        'plastic tray': 'You should put plastic tray into the black box.',
        'plastic trays': 'You should put plastic trays into the black box.',
        'food waste': 'You should put food waste into the brown box.',
        'peelings': 'You should put peelings into the brown box.',
        'leftovers': 'You should put leftovers into the brown box.',
        'meat bone': 'You should put meat bone into the brown box.',
        'meat bones': 'You should put meat bones into the brown box.',
        'fish bone': 'You should put fish bone into the brown box.',
        'fish bones': 'You should put fish bones into the brown box.',
        'egg sheel': 'You should put egg sheel into the brown box.',
        'egg sheels': 'You should put egg sheels into the brown box.',
        'tea bag': 'You should put tea bag into the brown box.',
        'tea': 'You should put tea into the brown box.',
        'tea leaves': 'You should put tea leaves into the brown box.',
        'tea grounds': 'You should put tea grounds into the brown box.',
        'coffee bag': 'You should put coffee bag into the brown box.',
        'coffee': 'You should put coffee into the brown box.',
        'coffee grounds': 'You should put coffee grounds into the brown box.',
        'garden waste': 'You should put garden waste into the brown box.',
        'grass cuttings': 'You should put grass cuttings into the brown box.',
        'twings': 'You should put twings into the brown box.',
        'grass': 'You should put grass into the brown box.',
        'leaves': 'You should put leaves into the brown box.',
        'compostable bag': 'You should put compostable bag into the brown box.',
        'compostable bags': 'You should put compostable bags into the brown box.',
        'branch': 'If the branch is smaller than 150 mm in diameter, you should put it into the brown box.',
        'branches': 'If the branch is smaller than 150 mm in diameter, you should put it into the brown box.',
        'bottle': 'If it is plastic bottle you should put it into the black box, if it is glass bottle you should put it into the red box.',
        'bottles': 'If it is plastic bottle you should put it into the black box, if it is glass bottle you should put it into the red box.',
        'jar': 'If it is glass jar you should put it into the red box, otherwise you should put it into the black refuse bin.',
        'jars': 'If it is glass jar you should put it into the red box, otherwise you should put it into the black refuse bin.',
        'tray': 'If it is aluminium or plastic tray, you should put it into the black box, otherwise you should put it into the black refuse bin.',
        'trays': 'If it is aluminium or plastic tray, you should put it into the black box, otherwise you should put it into the black refuse bin.',
        'bone': 'You should put animal bones into the brown box',
        'bones': 'You should put animal bones into the brown box.',
        'battery': 'You should take batteries to the houshold waste and recycling center',
        'batteries': 'You should take batteries to the houshold waste and recycling center',
        'CD': 'You should take CD to the houshold waste and recycling center',
        'DVD': 'You should take DVD to the houshold waste and recycling center',
        'disk': 'You should take disk to the houshold waste and recycling center',
        'oil': 'You should take oil to the houshold waste and recycling center',
        'cooking oil': 'You should take cooking oil to the houshold waste and recycling center',
        'ligthing tube': 'You should take ligthing tube to the houshold waste and recycling center',
        'fluorescent lighting tube': 'You should take fluorescent lighting tube to the houshold waste and recycling center',
        'tyre': 'You should take tyres to the houshold waste and recycling center',
        'tyres': 'You should take tyres to the houshold waste and recycling center',
        'wood': 'You should take wood to the houshold waste and recycling center',
        'tv': 'You should take tv to the houshold waste and recycling center',
        "monitor": 'You should take monitor to the houshold waste and recycling center',
        'figde': 'You should take figde to the houshold waste and recycling center',
        'freezer': 'You should take freezer to the houshold waste and recycling center',
        'rubble': 'You should take rubble to the houshold waste and recycling center',
    },
};
